# Generated by Django 4.2.5 on 2023-09-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_category_name_english', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria Prodotto',
                'verbose_name_plural': 'Categorie Prodotto',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('customer_unique_id', models.CharField(blank=True, default='', max_length=255)),
                ('customer_zip_code_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('customer_city', models.CharField(blank=True, default='', max_length=255)),
                ('customer_state', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_zip_code_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('geolocation_lat', models.FloatField(blank=True, default=0)),
                ('geolocation_lng', models.FloatField(blank=True, default=0)),
                ('geolocation_city', models.CharField(blank=True, default='', max_length=255)),
                ('geolocation_state', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Coordinata GEO',
                'verbose_name_plural': 'Coordinate GEO',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=255)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=255)),
                ('order_status', models.CharField(blank=True, default='', max_length=255)),
                ('order_purchase_timestamp', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('order_approved_at', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_olist.customer')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=255)),
                ('product_category_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_name_lenght', models.IntegerField(blank=True, default=0)),
                ('product_description_lenght', models.IntegerField(blank=True, default=0)),
                ('product_photos_qty', models.IntegerField(blank=True, default=0)),
                ('product_weight_g', models.FloatField(blank=True, default=0)),
                ('product_length_cm', models.FloatField(blank=True, default=0)),
                ('product_height_cm', models.FloatField(blank=True, default=0)),
                ('product_width_cm', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(blank=True, default='', max_length=255)),
                ('seller_zip_code_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('seller_city', models.CharField(blank=True, default='', max_length=255)),
                ('seller_state', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Venditore',
                'verbose_name_plural': 'Venditori',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(blank=True, default='', max_length=255)),
                ('payment_sequential', models.IntegerField(blank=True, default=0)),
                ('payment_type', models.CharField(blank=True, default='', max_length=255)),
                ('payment_installments', models.IntegerField(blank=True, default=0)),
                ('payment_value', models.FloatField(blank=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_olist.order')),
            ],
            options={
                'verbose_name': 'Pagamento Ordine',
                'verbose_name_plural': 'Pagamenti Ordine',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(blank=True, default='', max_length=255)),
                ('order_item_id', models.IntegerField(blank=True, default=0)),
                ('product_ref', models.CharField(blank=True, default='', max_length=255)),
                ('seller_ref', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_limit_date', models.DateTimeField(blank=True, default='1001-01-01 00:00:00')),
                ('price', models.FloatField(blank=True, default=0)),
                ('freight_value', models.FloatField(blank=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_olist.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_olist.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_olist.seller')),
            ],
            options={
                'verbose_name': 'Riga Ordine',
                'verbose_name_plural': 'Righe Ordine',
            },
        ),
    ]
