# Generated by Django 4.2.5 on 2023-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0002_alter_category_product_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_unique_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
