# Generated by Django 4.2.5 on 2023-09-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0003_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_id'], name='customer_id_idx'),
        ),
    ]
