# Generated by Django 4.2.5 on 2023-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0005_alter_order_customer_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivered_carrier_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivered_customer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_purchase_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
