# Generated by Django 4.2.5 on 2023-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0006_alter_order_order_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_id_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_unique_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
