# Generated by Django 4.2.5 on 2023-09-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0007_remove_customer_customer_id_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='order_status_idx'),
        ),
    ]
