# Generated by Django 4.2.5 on 2023-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0008_order_order_status_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'order_item_id'], name='order_item_idx'),
        ),
    ]
