# Generated by Django 4.2.5 on 2023-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0010_remove_orderitem_order_item_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order_ref', 'payment_sequential'], name='order_seq_payment_idx'),
        ),
    ]
