# Generated by Django 4.2.5 on 2023-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_olist', '0011_orderpayment_order_seq_payment_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='order_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
